// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"database/sql"
)

type Event struct {
	ID          int64
	StartTime   int64
	WindowClass string
	WindowTitle sql.NullString
	Duration    int64
}
