// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package dbgen

import (
	"context"
	"database/sql"
)

const getEvent = `-- name: GetEvent :one
SELECT id, start_time, window_class, window_title, duration
FROM event
WHERE id = ?
`

func (q *Queries) GetEvent(ctx context.Context, id int64) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.StartTime,
		&i.WindowClass,
		&i.WindowTitle,
		&i.Duration,
	)
	return i, err
}

const getEvents = `-- name: GetEvents :many
SELECT start_time, window_class, window_title, duration
FROM event
ORDER BY start_time DESC
`

type GetEventsRow struct {
	StartTime   int64
	WindowClass string
	WindowTitle sql.NullString
	Duration    int64
}

func (q *Queries) GetEvents(ctx context.Context) ([]GetEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, getEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEventsRow
	for rows.Next() {
		var i GetEventsRow
		if err := rows.Scan(
			&i.StartTime,
			&i.WindowClass,
			&i.WindowTitle,
			&i.Duration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventsByTime = `-- name: GetEventsByTime :many
SELECT start_time, window_class, window_title, duration
FROM event
WHERE start_time BETWEEN ?1 AND ?2
ORDER BY start_time DESC
`

type GetEventsByTimeParams struct {
	StartTime int64
	EndTime   int64
}

type GetEventsByTimeRow struct {
	StartTime   int64
	WindowClass string
	WindowTitle sql.NullString
	Duration    int64
}

func (q *Queries) GetEventsByTime(ctx context.Context, arg GetEventsByTimeParams) ([]GetEventsByTimeRow, error) {
	rows, err := q.db.QueryContext(ctx, getEventsByTime, arg.StartTime, arg.EndTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEventsByTimeRow
	for rows.Next() {
		var i GetEventsByTimeRow
		if err := rows.Scan(
			&i.StartTime,
			&i.WindowClass,
			&i.WindowTitle,
			&i.Duration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertEvents = `-- name: InsertEvents :exec
INSERT INTO event (start_time, window_class, window_title, duration)
VALUES (?, ?, ?, ?)
`

type InsertEventsParams struct {
	StartTime   int64
	WindowClass string
	WindowTitle sql.NullString
	Duration    int64
}

func (q *Queries) InsertEvents(ctx context.Context, arg InsertEventsParams) error {
	_, err := q.db.ExecContext(ctx, insertEvents,
		arg.StartTime,
		arg.WindowClass,
		arg.WindowTitle,
		arg.Duration,
	)
	return err
}
